### PR TITLE
Add whoops debugger

### PR DESCRIPTION
**Pull request by vinkla**
This will give us much prettier error messages.

### CODE REVIEW

**Comment by mikaelmattsson** [comment]
I don't make errors. My code allways works.

**Comment by vinkla** [comment]
face palm

**Comment by mikaelmattsson** [comment]
Dog

**Comment by magnus-bergman** [comment]
just came here to read the comments

**Comment by vinkla** [comment]
dog_41

**Comment by olleman42** [comment]
slutanu

**Comment by magnus-bergman** [comment]
Hej Sergey :+1:

**Comment by mikaelmattsson** [comment]
HEY

**Pull request merged**
